from __future__ import annotations

from collections.abc import Iterable, Sequence
from typing import Protocol, TypeVar

from pydantic import BaseModel

from polygraphml.domain.models import Audit, AuditEvent, Session

ModelT = TypeVar("ModelT", bound=BaseModel)


class DomainRepository(Protocol):
    def close(self) -> None: ...

    def create_session(self, ttl_seconds: int) -> tuple[Session, str]: ...

    def get_session_by_token(self, token: str) -> Session | None: ...

    def put(self, model: ModelT) -> ModelT: ...

    def get(self, model_type: type[ModelT], object_id: str) -> ModelT | None: ...

    def list(self, model_type: type[ModelT], parent_id: str | None = None) -> list[ModelT]: ...

    def count_projects(self, session_id: str) -> int: ...

    def count_active_audits(self, session_id: str) -> int: ...

    def get_idempotent_result(self, scope: str, key: str) -> str | None: ...

    def record_idempotent_result(self, scope: str, key: str, result_id: str) -> None: ...

    def append_event(self, audit: Audit, event: AuditEvent) -> AuditEvent: ...

    def list_events(self, audit_id: str, after_sequence: int = 0) -> Sequence[AuditEvent]: ...

    def event_sequence(self, audit_id: str, event_id: str) -> int | None: ...

    def acquire_audit_lease(self, audit_id: str, owner: str, lease_seconds: int) -> bool: ...

    def release_audit_lease(self, audit_id: str, owner: str) -> None: ...

    def delete_project(self, project_id: str) -> None: ...

    def seed(self, models: Iterable[BaseModel]) -> None: ...
